buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'java'

version = project.mod_version
group = 'dev.briefestboxer'
archivesBaseName = 'briefest-boxer-1.9.4-forge'

sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    version = '1.9.4-12.17.0.2317-1.9.4'
    runDir = 'run'
    mappings = 'stable_26'
}

sourceSets.main.java.srcDir('../../../common/src/main/java')
sourceSets.main.java.exclude('dev/briefestboxer/core/SulfurCubeHitModel.java')

processResources {
    inputs.property 'version', project.version
    filesMatching('mcmod.info') { expand 'version': project.version }
}

jar {
    manifest { attributes 'FMLCorePluginContainsFMLMod': 'true' }
}

reobf {
    jar {
        mappingType = 'SEARGE'
    }
}

// Include the project license and the GPL terms incorporated by LGPL 3.0.
jar {
    from('../../../') {
        include 'LICENSE', 'COPYING'
    }
}
