modLoader="javafml"
loaderVersion="[65,)"
license="LGPL-3.0-only"

[[mods]]
modId="briefest_boxer"
version="${file.jarVersion}"
displayName="Briefest Boxer"
description='''Visible reachable entity hitboxes and adult Sulfur Cube trajectory preview.'''

[[dependencies.briefest_boxer]]
modId="forge"
mandatory=true
versionRange="[65.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.briefest_boxer]]
modId="minecraft"
mandatory=true
versionRange="[26.2,26.3)"
ordering="NONE"
side="CLIENT"
