modLoader="javafml"
loaderVersion="[54,)"
license="All Rights Reserved"

[[mods]]
modId="briefest_boxer"
version="${file.jarVersion}"
displayName="Briefest Boxer"
description='''Highlights the reachable, visible surfaces of nearby entities.'''

[[dependencies.briefest_boxer]]
modId="forge"
mandatory=true
versionRange="[54.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.briefest_boxer]]
modId="minecraft"
mandatory=true
versionRange="[1.21.4,1.21.5)"
ordering="NONE"
side="CLIENT"
