buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies { classpath 'net.minecraftforge.gradle:ForgeGradle:5.1.+' }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'

version = mod_version
group = 'dev.briefestboxer'
archivesBaseName = "briefest-boxer-${minecraft_version}-forge"
sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20210309-1.16.5'
    runs {
        client { workingDirectory project.file('run') }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

sourceSets.main.java.srcDir('../../../common/src/main/java')
sourceSets.main.java.exclude('dev/briefestboxer/core/SulfurCubeHitModel.java')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// Include the project license and the GPL terms incorporated by LGPL 3.0.
jar {
    from('../../../') {
        include 'LICENSE', 'COPYING'
    }
}
