modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
[[mods]]
modId="briefest_boxer"
version="${file.jarVersion}"
displayName="Briefest Boxer"
description='''Client-side player aim-point guide.'''
[[dependencies.briefest_boxer]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.briefest_boxer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"
