modLoader="javafml"
loaderVersion="[52,)"
license="All Rights Reserved"

[[mods]]
modId="briefest_boxer"
version="${file.jarVersion}"
displayName="Briefest Boxer"
description='''Client-side player aim points.'''

[[dependencies.briefest_boxer]]
modId="forge"
mandatory=true
versionRange="[52.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.briefest_boxer]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="CLIENT"
