modLoader="javafml"
loaderVersion="[52,)"
license="LGPL-3.0-only"

[[mods]]
modId="briefest_boxer"
version="${file.jarVersion}"
displayName="Briefest Boxer"
description='''Highlights the reachable, visible surfaces of nearby entities.'''

[[dependencies.briefest_boxer]]
modId="forge"
mandatory=true
versionRange="[52.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.briefest_boxer]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="CLIENT"
