modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="briefest_boxer"
version="${file.jarVersion}"
displayName="Briefest Boxer"
description='''Client-side player aim points.'''

[[dependencies.briefest_boxer]]
modId="forge"
mandatory=true
versionRange="[47.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.briefest_boxer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"
