plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'legacy-looming' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

repositories {
    maven { url = 'https://repo.legacyfabric.net/legacyfabric' }
}

loom {}

legacyLooming {
    intermediaryVersion = 1
}

sourceSets.main.java.srcDir('../../../common/src/main/java')
sourceSets.main.java.srcDir('src/client/java')
sourceSets.main.java.exclude('dev/briefestboxer/core/SulfurCubeHitModel.java')

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings legacy.yarn(project.minecraft_version, project.yarn_build)
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
}
